name: Build Windows EXE

on:
  push:
    branches:
      - main   # 或你默认的分支名

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'  # 可调整 Go 版本

      - name: Build Windows executable
        run: |
          GOOS=windows GOARCH=amd64 go build -o MockServer.exe main.go

      - name: Upload artifact
        uses: actions/upload-artifact@v4  # ✅ 已更新版本
        with:
          name: MockServer-exe
          path: MockServer.exe
